---
name: Gitlint
on:
  pull_request:
    branches:
    - gh-readonly-queue/**
    - $default-branch
jobs:
  commit-message-style:
    if: github.triggering_actor != 'dependabot[bot]'
    name: Check commit message style
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install gitlint
      run: pip install --user gitlint
    - name: Validate commit messages
      run: gitlint --commits ${{ github.event.pull_request.base.sha }}..HEAD
