---
name: Terraform
on:
  pull_request:
    branches:
    - gh-readonly-queue/**
    - $default-branch
jobs:
  terraform:
    name: Check Terraform configuration style
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      TF_IN_AUTOMATION: 1
      TF_INPUT: 0
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: <2.0.0
    - name: Validate Terraform configuration
      id: fmt
      run: terraform fmt -check -recursive -diff
